version: "3.8"

services:
  financemanagerapi:
    build:
      context: .
      dockerfile: FinanceManagerApi/Dockerfile
    container_name: financemanagerapi
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-data:/data/letsencrypt
    depends_on:
      - financemanagerapi
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-data:/data/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
