version: "3.8"

services:
  financemanagerapi:
    build:
      context: .
      dockerfile: FinanceManagerApi/Dockerfile
    container_name: financemanagerapi
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8082:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-data:/data/letsencrypt
    depends_on:
      - financemanagerapi
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-data:/data/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
